name: Run tests on push

on:
  push:
    branches: ["*"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run App
      run: docker-compose up -d --build

    - name: Run tests
      run: docker-compose exec api python manage.py test

    - name: Drop all
      run: docker-compose down -v --remove-orphans